language: elixir

sudo: required

os:
  - "linux"
  - "osx"

elixir:
  - 1.3.0

otp_release:
  - 19.0.0

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - "sleep 10"

install:
    - ./.travis/install.sh
    - npm install
    - ./bin/microcrawler config init
